/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnicasRouteImport } from './routes/tecnicas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as ExploraRouteImport } from './routes/explora'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TecnicasRoute = TecnicasRouteImport.update({
  id: '/tecnicas',
  path: '/tecnicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploraRoute = ExploraRouteImport.update({
  id: '/explora',
  path: '/explora',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/explora': typeof ExploraRoute
  '/habitos': typeof HabitosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tecnicas': typeof TecnicasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/explora': typeof ExploraRoute
  '/habitos': typeof HabitosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tecnicas': typeof TecnicasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/explora': typeof ExploraRoute
  '/habitos': typeof HabitosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tecnicas': typeof TecnicasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajustes'
    | '/explora'
    | '/habitos'
    | '/reset-password'
    | '/tecnicas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajustes'
    | '/explora'
    | '/habitos'
    | '/reset-password'
    | '/tecnicas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajustes'
    | '/explora'
    | '/habitos'
    | '/reset-password'
    | '/tecnicas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjustesRoute: typeof AjustesRoute
  ExploraRoute: typeof ExploraRoute
  HabitosRoute: typeof HabitosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TecnicasRoute: typeof TecnicasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnicas': {
      id: '/tecnicas'
      path: '/tecnicas'
      fullPath: '/tecnicas'
      preLoaderRoute: typeof TecnicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explora': {
      id: '/explora'
      path: '/explora'
      fullPath: '/explora'
      preLoaderRoute: typeof ExploraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjustesRoute: AjustesRoute,
  ExploraRoute: ExploraRoute,
  HabitosRoute: HabitosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TecnicasRoute: TecnicasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
